all:
	@cd src && $(MAKE)
	@cp src/sudoku .

clean:
	@cd src && $(MAKE) clean
	@rm -f sudoku

report:
	@cd report && pdflatex main.tex
	
help:
	@echo "Usage:"
	@echo " make [all]\t\tBuild the software"
	@echo " make clean\t\tRemove all files generated by make"
	@echo " make help\t\tDisplay this help"
	@echo " make report\t\tGenerate a software's report"

.PHONY: all clean report help 
